FROM node:22.12.0-alpine AS build
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run build

FROM node:22.12.0-alpine AS production
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /usr/src/app/dist ./dist

# 1) Cria a pasta de logs ANTES de virar usuário node
RUN mkdir ./logs && chown node:node ./logs

USER node

# 2) Você pode remover o EXPOSE ou alinhar com o PORT default da sua app
# EXPOSE 8000

CMD ["node", "dist/index.js"]
