FROM node:22.12.0-alpine AS build

WORKDIR /usr/src/app

COPY package*.json ./

# Instala tudo (prod + dev)
RUN npm ci

COPY . .

# Executa build
RUN npm run build

# Agora só copiar o resultado e as deps de produção para a imagem final
FROM node:22.12.0-alpine AS production

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm ci --omit=dev

COPY --from=build /usr/src/app/dist ./dist

USER node

EXPOSE 8080

CMD ["node", "dist/index.js"]
