# Usando Node v22-alpine para dev (menor imagem)
FROM node:22-alpine AS dev

WORKDIR /usr/src/app

# Instala as dependências (incluindo dev)
COPY package*.json ./
RUN npm install

# Copia o código fonte para dentro do container
COPY . .

# Expõe porta do app e do debug do node
EXPOSE 8080
EXPOSE 9229

# Comando para rodar com nodemon + tsx (conforme seu package.json)
CMD ["npm", "run", "dev"]
